// Auto-generated macro registry
// This file is automatically generated by scripts/generate-macro-index.js
// DO NOT EDIT MANUALLY - run 'npm run generate-macros' to regenerate

// Discovered macro files: active_setting_lore, candidate_entries, candidate_registry, current_running_recap, earliest_allowed_break, entry_name, existing_content, lorebook_entry_lookup_synopsis, lorebook_entry_types, message, messages, minimum_scene_length, new_content, new_entries, new_entry, prefill, scene_messages, scene_recaps
const macroFiles = [
  "active_setting_lore",
  "candidate_entries",
  "candidate_registry",
  "current_running_recap",
  "earliest_allowed_break",
  "entry_name",
  "existing_content",
  "lorebook_entry_lookup_synopsis",
  "lorebook_entry_types",
  "message",
  "messages",
  "minimum_scene_length",
  "new_content",
  "new_entries",
  "new_entry",
  "prefill",
  "scene_messages",
  "scene_recaps"
];

// Dynamic import and registration
const macroModules = await Promise.all(
  macroFiles.map(file => import(`./${file}.js`))
);

// Build MACRO_NAMES object from all modules
export const MACRO_NAMES = {};
for (const mod of macroModules) {
  const upperName = mod.name.toUpperCase().replace(/-/g, '_');
  MACRO_NAMES[upperName] = mod.name;
}

// Build macroDescriptions for documentation
export const macroDescriptions = {};
for (const mod of macroModules) {
  macroDescriptions[mod.name] = mod.description;
}

// Validation wrapper for macro builders
function validateMacroResult(macroName, args, result) {
  const isEmpty = result === null || result === undefined || result === '';

  if (isEmpty) {
    console.error(`[MACRO ERROR] Macro '${macroName}' returned empty result!`);
    console.error(`  Input args:`, args);
    console.error(`  Result:`, result);
    console.error(`  Stack trace:`, new Error(`Macro ${macroName} validation failed`).stack);
  }

  return result;
}

// Build macroBuilders object with validation wrappers
export const macroBuilders = {};
for (const mod of macroModules) {
  const originalBuilder = mod.build;
  macroBuilders[mod.name] = function(...args) {
    const result = originalBuilder(...args);
    return validateMacroResult(mod.name, args, result);
  };
}

// Helper to get builder by name
export function getMacroBuilder(macroName) {
  return macroBuilders[macroName];
}

// Helper to build macro value
export function buildMacroValue(macroName, ...args) {
  const builder = getMacroBuilder(macroName);
  if (!builder) {
    throw new Error(`No builder found for macro: ${macroName}`);
  }
  return builder(...args);
}

// Re-export substitute functions from promptUtils
export { substitute_params, substitute_conditionals, substitute_params_and_builtin } from '../promptUtils.js';
